vim.cmd('syntax on')
vim.cmd('filetype plugin indent on')

vim.cmd('set updatetime=300')
vim.cmd('set encoding=utf-8')
vim.cmd('set shortmess+=c')

vim.cmd('set hidden')
vim.cmd('set clipboard=unnamed')
vim.cmd('set exrc')
vim.cmd('set guicursor=')
vim.cmd('set relativenumber')
vim.cmd('set nohlsearch')
vim.cmd('set hidden')
vim.cmd('set noerrorbells')
vim.cmd('set tabstop=4 softtabstop=4')
vim.cmd('set shiftwidth=4')
vim.cmd('set expandtab')
vim.cmd('set smartindent')
vim.cmd('set nu')
vim.cmd('set nowrap')
vim.cmd('set smartcase')
vim.cmd('set nobackup')
vim.cmd('set undodir=C:/Users/cristiano.moraes/AppData/Local/nvim/undodir')
vim.cmd('set undofile')
vim.cmd('set incsearch')
vim.cmd('set termguicolors')
vim.cmd('set scrolloff=8')
vim.cmd('colorscheme gruvbox')
